### ISSUE TITLE
Rear right steppers do not move on hybrid config while X axis movement

### ISSUE THREAD

**Issue by macke4ever** [Rat-Rig/V-CoreOS#130] opened 2024-06-02 19:24 UTC
### What happened

V-core 4 500mm hybrid setup, when configured to work as hybrid some stepper motors do not move. Y axis works fine, while X axis rotates only left side steppers. Thus toolhead moves diagonaly only

### What did you expect to happen

When toolhead moved in X axis all 4 rear steppers should rotate

### How to reproduce

Rat OS 2.1, vcore 4 500mm, hybrid configuration. Move toolhead left/right.

**Comment by Myles5588** [comment] 2024-06-09 14:30
Wiring diagram appears to not match up with what is in the printer.cfg file.  Match your stepper/board wiring to what is in the printer.cfg file.  I found I had to switch motor1 and motor4 on my octopus board.

**Comment by miklschmidt** [comment] 2024-06-13 18:19
I forgot to reply on this. The problem is indeed the official RR wiring diagram is incorrect (it will be fixed). You can remap your steppers using "advanced stepper configuration" in the configurator, or move the cables around. For hybrid the order (from left to right) is X(A), Y, E,X1(B),Y1.

**Closed as completed by miklschmidt** 2024-06-13 18:19 UTC
Labels: bug
