### ISSUE TITLE
Built in filament unload causing clogs

### ISSUE THREAD

**Issue by smwoodward-beep** [Rat-Rig/V-CoreOS#138] opened 2024-06-25 22:07 UTC
### What happened

The tip forming dipping done prior to fully ejecting the filament with an Orbiter 2 and Phaetus UHF Rapido pulls up molten filament when ejecting into the bowden tube between extruder and hot end, cools and hardens.

### What did you expect to happen

The filament should eject cleanly

### How to reproduce

Fairly obvious.

**Comment by HelgeKeck** [comment] 2024-06-25 23:35
This is not a bug.

RatOS V2.1 has a inbuilt tip forming protocol before it unlaods a filament. it comes with default values that work for msot people, but its not possible to provide settings for every situation, this depends heavily on used nozzle, filament brand and type and selected temperature.

depending you your configuration you need to override the tip forming parameters for your situation, for example if you use a UHF CHT nozzle then you override `_UNLOAD_UHF_CHT` in your prionter.cfg

```
[gcode_macro _UNLOAD_UHF_CHT]
gcode:
	# parameter
	{% set toolhead = params.TOOLHEAD|int %}

	DEBUG_ECHO PREFIX="_UNLOAD_UHF_CHT" MSG="TOOLHEAD: {toolhead}"

	_TIP_FORMING RETRACT_LENGTH=18 COOLING_MOVE_LENGTH=10 DIP=False

```


@miklschmidt requesting to close this since its not a bug

**Comment by smwoodward-beep** [comment] 2024-06-25 23:37
Should these not be variables instead of the user needing to override a full macro?

**Comment by HelgeKeck** [comment] 2024-06-25 23:38
> Should these not be variables instead of the user needing to override a full macro?

no, it is handled depending on the used nozzle size and type, there are several of these small macros you can override, this is easier than to provide variables for all different nozzle types

**Comment by HelgeKeck** [comment] 2024-06-25 23:38
if you need more informations i suggest to ask in the discord server

**Comment by smwoodward-beep** [comment] 2024-06-25 23:40
> if you need more informations i suggest to ask in the discord server

Yeah I would love to do that, but I got booted from there because you insulted me telling me I was pissing people off when I told you that over writting ratos.cfg would piss people off.

**Comment by smwoodward-beep** [comment] 2024-06-25 23:40
So until such time as I could use the discord server, I will do that here.

**Comment by HelgeKeck** [comment] 2024-06-25 23:41
i did not insulted you and this is place is purely for bug discussions.

@miklschmidt requesting a close

**Comment by smwoodward-beep** [comment] 2024-06-25 23:42
> i did not insulted you and this is place is purely for bug discussions.
> 
> @miklschmidt requesting a close

This is a bug, and yes you did insult me.

**Comment by smwoodward-beep** [comment] 2024-06-25 23:44
> i did not insulted you and this is place is purely for bug discussions.
> 
> @miklschmidt requesting a close

Now if you would like for me to discuss this in Discord instead of here, let me back in.  Any and all issues I have with RatOS from here forward will be made here otherwise. And I will open a bug for anything and everything even without doing any troubleshooting prior to it.

**Closed as completed** 2024-06-25 23:49 UTC
Labels: bug
